source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'
pod 'PayPal-iOS-SDK'
pod 'FBSDKCoreKit'
pod 'FBSDKMessengerShareKit'
pod 'FBSDKLoginKit'
pod 'ZXingObjC', '~>3.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'iOS-Color-Picker'
